// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwuxgpyorphgcopzrqna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3dXhncHlvcnBoZ2NvcHpycW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExOTQ1MTIsImV4cCI6MjA1Njc3MDUxMn0.qXnnU1IROOHKMvYswlAiweb9QHrU-aEx-mTf1KvwKuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);